### ISSUE TITLE
Should we add more page subtitles & introductions?

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#42]
Should we add subtitles to each page [under the title](https://contributor.r-project.org/cran-cookbook/docs_issues.html) with the recipes and possibly an overview of what the collection of recipes features as a intro paragraph?

**Comment by Baltmann01** [comment]
I like this idea. Right now the space seems a bit empty. Adding some form of intro to the group of recipes sounds great to fill this void. I don't know how much a TOC or list of recipes makes sense though since we already have the "On this page" TOC on the right of the website. 
Maybe we can think of what to put there and discuss in our next meeting?
